/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./App.tsx", "./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#643f00",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e1e3e4",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "outline-variant": "#bfcaba",
        "secondary-fixed-dim": "#a9c7ff",
        "outline": "#707a6c",
        "surface-container-high": "#e7e8e9",
        "tertiary-fixed-dim": "#ffb957",
        "on-surface": "#191c1d",
        "primary-fixed-dim": "#88d982",
        "on-secondary-fixed-variant": "#00468c",
        "on-primary-fixed-variant": "#005312",
        "primary-fixed": "#a3f69c",
        "on-tertiary-container": "#ffeede",
        "primary": "#0d631b",
        "secondary": "#005db7",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary-fixed": "#001b3d",
        "surface-bright": "#f8f9fa",
        "tertiary": "#774c00",
        "surface": "#f8f9fa",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#002204",
        "on-secondary-container": "#003670",
        "surface-container-highest": "#e1e3e4",
        "inverse-primary": "#88d982",
        "surface-container": "#edeeef",
        "on-tertiary-fixed": "#2a1800",
        "surface-dim": "#d9dadb",
        "inverse-surface": "#2e3132",
        "background": "#f8f9fa",
        "on-secondary": "#ffffff",
        "tertiary-container": "#986200",
        "tertiary-fixed": "#ffddb5",
        "primary-container": "#2e7d32",
        "secondary-fixed": "#d6e3ff",
        "on-primary-container": "#cbffc2",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1d",
        "surface-tint": "#1b6d24",
        "secondary-container": "#64a1ff",
        "on-surface-variant": "#40493d",
        "surface-container-low": "#f3f4f5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "1rem",
        "container-margin-mobile": "1rem",
        xl: "2rem",
        xs: "0.25rem",
        gutter: "1rem",
        "2xl": "3rem",
        lg: "1.5rem",
        sm: "0.5rem",
        base: "8px",
        "container-margin-desktop": "2.5rem",
      },
    },
  },
  plugins: [],
};